FROM python:3.9

# Set working directory
WORKDIR /app

# Install only necessary dependencies for testing
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project (including tests and src)
COPY . .

# Default command to run tests
CMD ["python", "-m", "unittest", "discover", "-s", "tests"]
