services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    shm_size: 2gb
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://selenium:4444/status" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    env_file:
      - .env

  webscrape:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: webscrape
    depends_on:
      selenium:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./src/input:/app/src/input
      - ./src/output:/app/src/output
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    command: [ "python", "/app/src/core/main.py" ]
