services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/status" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s

  chrome:
    image: seleniarm/node-chromium:latest
    container_name: selenium-node-chrome
    depends_on:
      selenium-hub:
        condition: service_healthy
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  login:
    build:
      context: .
      dockerfile: Dockerfile.login
    container_name: hafele_login
    depends_on:
      selenium-hub:
        condition: service_healthy
      chrome:
        condition: service_started
    volumes:
      - ./shared:/shared
    env_file:
      - .env
    command: [ "python", "/app/src/hafele_login/login_loop.py" ]

  webscrape:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    container_name: webscrape
    depends_on:
      login:
        condition: service_started
    volumes:
      - ./shared:/shared
      - ./src/input:/src/input
      - ./src/output:/src/output
    env_file:
      - .env
    command: [ "python", "/app/src/scraper/scraper_loop.py" ]
