services:
  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    shm_size: 2gb
    ports:
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://selenium:4444/status" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    env_file:
      - .env

  flask_service:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: auth_service
    ports:
      - "5001:5001"
    depends_on:
      selenium:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src/input:/app/src/input
    command: [ "/bin/sh", "-c", "chmod +x /app/src/input/start.sh && /app/src/input/start.sh" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:5001/health" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

  request_operations:
      build:
        context: .
        dockerfile: Dockerfile.auth
      container_name: request_operations
      depends_on:
        flask_service:
          condition: service_healthy
      env_file:
        - .env
      volumes:
        - ./src/input:/app/src/input
      command: [ "python", "-u", "/app/src/input/api.py" ]

  shutdown_auth:
      image: docker:latest
      container_name: shutdown_auth
      depends_on:
        request_operations:
          condition: service_completed_successfully
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: [ "sh", "-c", "docker stop auth_service" ]

  webscrape:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: webscrape
      depends_on:
        request_operations:
          condition: service_completed_successfully
        selenium:
          condition: service_healthy
      env_file:
        - .env
      environment:
        - GRID_URL=http://selenium:4444/wd/hub
      volumes:
        - ./src/input:/src/input
        - ./src/output:/src/output
      command: [ "python", "/app/src/core/main.py" ]
