services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    depends_on:
      request_operations:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/status" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s

  chrome:
      image: seleniarm/node-chromium:latest
      container_name: selenium-node-chrome
      depends_on:
        selenium-hub:
          condition: service_healthy
      environment:
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  webscrape:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: webscrape
      depends_on:
        request_operations:
          condition: service_completed_successfully
        selenium-hub:
          condition: service_healthy
        chrome:
          condition: service_started
      env_file:
        - .env
      environment:
        - GRID_URL=http://selenium-hub:4444/wd/hub
      volumes:
        - ./src/input:/src/input
        - ./src/output:/src/output
      command: [ "python", "/app/src/main.py" ]
